### ISSUE TITLE
Use grommet as a library

### ISSUE THREAD

**Issue by Spy-Seth** [grommet/grommet#197]
First of all guys: I :heart: your UI!

I trying to use it as a dependent library of my project: `var Dashboard = require('grommet').Dashboard`. But right now it's impossible, you do not provide a compiled version of the source in the npm package. 

Is it possible to distribute builded source with your next (or next next) release?

The SCSS files will to be compiled to CSS too.

**Comment by alansouzati** [comment]
hi @Spy-Seth, thanks for the kind words about Grommet.

The browser version of Grommet (compiled scss and js) can be found on Bower: `bower install grommet`.

The NPM distribution is dependent on React and JSX. I believe you are facing issues like `module react not found`? We don't have planned to add compiled version in NPM itself, do you have examples of other projects doing that for us to evaluate this? Initially it sounds like bower to me, but I may be wrong here.

**Comment by Spy-Seth** [comment]
>  I believe you are facing issues like module react not found?
Nop a syntax error. The JSX compiler (Babel) do not apply on files located in the `node_modules` directory.

Bower was originally made to mange front package while NPM manage nodejs package. But nowadays, NPM is also use with front package (mainly to avoid to mange to dependency manager). Lot's of library distribute itself on both. For example: https://github.com/twbs/bootstrap (only with the styles, but this is the idea). Or another example with a React UI library only on NPM https://github.com/react-bootstrap/react-bootstrap

**Comment by alansouzati** [comment]
Are you using webpack? Can you add grommet to your babel configuration? If you are using the Grommet developer environment this configuration comes by default to you.

We are concerned about providing the compiled version for NPM at this point. One of the reasons being performance optimizations.

We would rather have `require('grommet/components/Meter')` as opposed to `require('grommet').Meter`.

I know we could provide a compiled version for each of these components separately, but it adds more complexity to the build environment. We believe that it is just simpler to add grommet to your babel configuration.

**Comment by Spy-Seth** [comment]
> Are you using webpack?

I'm using browserify.

> I know we could provide a compiled version for each of these components separately, but it adds more complexity to the build environment. We believe that it is just simpler to add grommet to your babel configuration.

Adding grommet to my babel configuration is not a long term solution. Imagine if every package on npm ask to do it: the build time for a project will huge! And the configuration of our build process will be extremely complicated.

I've look into the Grommet build process. The `dist-bower` task is really close to a `dist-npm` task.

I really think adding a compiled version is a good thing for the project. It will allow you to reach more user. And if you go all the way down, and propose `require('grommet').Box` it will help you to ensure the components are well done and decoupled.

**Comment by alansouzati** [comment]
Thanks for your explanation. I agree with this part:

>  Adding grommet to my babel configuration is not a long term solution.

 I have some ideas around this that I want to explore.

 I will get back to you on this.

**Comment by mattbrewer-educredu** [comment]
I'd also love it if you guys made a compiled version of grommet available. I came across Grommet a few weeks ago while looking for some react charting components and found a few other components and that I didn't realize I needed.

I've compiled my own local versions of the Grommet components, but it was a little more work than I would have liked, and I'm probably limiting myself because I don't plan on going through that process again so I won't be able to leverage any patches or updates until you guys ship precompiled components.

Anyways, the only reason I went through the hassle of getting the components compiled was to use them with React UI Builder (https://github.com/ipselon/react-ui-builder), and they work great with it. The UI builder is good for throwing together some quick mock ups. I think if you guys get the compiled components going you should spend some time getting them into the UI builder, it could get you some extra visibility. 

I really like what you guys have put together here, thanks for making it open source. 

P.S - Is there actually a Grommet blog? The current link on the site links to the get started page, and I'd love to get my Grommet updates in RSS fashion.

**Comment by alansouzati** [comment]
Hi @mattbrewer-educredu, thanks for the extra input here. I have this issue as one of my items to tackle in the next days or so. So expect to hear news about that soon.

Thanks for sharing React UI builder with us, will definitely take a look into that.

There is no Grommet blog at this point, sorry about that. We are working on it. In the meantime I invite you to join our [Slack channel](http://grommet.io/slackin). We constantly post updates and news there.

**Comment by alansouzati** [comment]
Thanks for the feedback folks. I've fixed that here: https://github.com/HewlettPackard/grommet/commit/7f806d61b260a07a570d0f8ac7636538b61f60f4.

It will be available in the next release. In the meantime you can use grommet [stable](https://github.com/HewlettPackard/grommet/tree/stable) to immediately get these changes. Keep in mind that grommet stable gets updated every time that someone commits something and passes the CI build. To get that update your package.json as follows:

```
{
  ...
  dependencies:  {
    "grommet": "https://github.com/HewlettPackard/grommet.git#stable"
  }
}
```

Let me know if it works so that we can close this issue :+1:

**Comment by Spy-Seth** [comment]
I can't test it this week, but that a greet news! 

![:+1:](https://media.giphy.com/media/MTclfCr4tVgis/giphy.gif)

**Comment by Spy-Seth** [comment]
Hum I cannot completely test it. My application is a isomorphic react app. And the Grommet code is not isomorphic:  it depend directly on browser API.

```
/Users/spy-seth/workspace/rescue/node_modules/grommet/utils/Cookies.js:37
    return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*" + encodeURIComponent(sKey).replace(/[\-\.\+\*]/g, "\\$&") + "\\s*\\=\\s*([^;]*).*$)|^.*$"), "$1")) || null;
```

I will have another look later.

**Comment by alansouzati** [comment]
We should support isomorphic. This is definitely an issue to be solved!

**Comment by Spy-Seth** [comment]
I'm glad you said this :+1:

**Comment by alansouzati** [comment]
Hi @Spy-Seth that is really strange. Is there any place calling `Cookie.get` in your app?

In theory it should be ok to have this code in side NPM and serve-side as long as you are only invoking inside a `componentDidMount` for example.

Let me know if this call is coming from a Grommet component somehow...

**Comment by Spy-Seth** [comment]
Ho I haven't put the full stack trace. My bad. 

```
/Users/spy-seth/workspace/rescue-dashboard/node_modules/grommet/utils/Cookies.js:47
    return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*" + encodeURIComponent(sKey).replace(/[\-\.\+\*]/g, "\\$&") + "\\s*\\=\\s*([^;]*).*$)|^.*$"), "$1")) || null;
                              ^

ReferenceError: document is not defined
    at Object.get (/Users/spy-seth/workspace/rescue-dashboard/node_modules/grommet/utils/Cookies.js:47:31)
    at Store.init (/Users/spy-seth/workspace/rescue-dashboard/node_modules/grommet/stores/SessionStore.js:25:29)
    at new Store (/Users/spy-seth/workspace/rescue-dashboard/node_modules/reflux-core/lib/createStore.js:48:18)
    at Object.module.exports [as createStore] (/Users/spy-seth/workspace/rescue-dashboard/node_modules/reflux-core/lib/createStore.js:60:17)
    at Object.<anonymous> (/Users/spy-seth/workspace/rescue-dashboard/node_modules/grommet/stores/SessionStore.js:14:27)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/spy-seth/workspace/rescue-dashboard/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/spy-seth/workspace/rescue-dashboard/node_modules/grommet/index.js:77:17)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/spy-seth/workspace/rescue-dashboard/node_modules/babel-core/lib/api/register/node.js:214:7)
```

We can see that in the session store initialization you do a lot of `Cookie.get`: https://github.com/grommet/grommet/blob/581840f3e29c9d2ed531261ef5c4182fd15c4e60/src/js/stores/SessionStore.js#L23-L26

**Comment by primozs** [comment]
To make it work like a library I needed grommet stable and
```{
  ...
  dependencies:  {
    "grommet": "https://github.com/HewlettPackard/grommet.git#stable"
  }
}
```
also root setting in webpack
```
  resolve: {
    modulesDirectories: [
      "src",
      "node_modules"
    ],
    root: [
      path.resolve(__dirname, 'node_modules'),
      path.resolve(__dirname, 'src'),
    ],
    extensions: ['', '.js', '.jsx', '.scss']
  },
```
cheers

**Comment by AngusMackHPE** [comment]
@primozs - can you send a sample of your complete webpack config and component file please? I'm stuck getting this to work.

**Comment by primozs** [comment]
@AngusMackHPE 
To get everything to work, I installed stable branch. Check also all the dependencies that usual grommet application need. This will also not work with React 0.14.0 only with 0.13.3. When I tried Grommet "react14" branch I again could not require Grommet components, my webpack config was not working. 

```
$ grommet init sample-app
```

It looks to me that somehow minimum dependencies for client app would be something like this:
```
"body-parser": "1.14.1",
    "grommet": "git+https://github.com/HewlettPackard/grommet.git#73f83edf5b1a143e9f1b29cfa28e01fe46fe40d4",
    "intl": "^1.0.0",
    "inuit-box-sizing": "~0.2.0",
    "inuit-clearfix": "^0.2.1",
    "inuit-defaults": "~0.2.1",
    "inuit-functions": "~0.2.0",
    "inuit-headings": "~0.3.0",
    "inuit-images": "~0.3.3",
    "inuit-list-bare": "~0.3.0",
    "inuit-lists": "~0.1.0",
    "inuit-mixins": "~0.2.3",
    "inuit-normalize": "~3.0.2",
    "inuit-page": "~0.2.1",
    "inuit-reset": "~0.1.1",
    "inuit-responsive-settings": "~0.1.2",
    "inuit-responsive-tools": "~0.1.1",
    "inuit-shared": "~0.1.5",
    "lodash": "^3.8.0",
    "moment": "^2.8.3",
    "react": "0.13.3",
    "react-gravatar": "^2.0.0",
    "react-intl": "1.2.1",
    "react-router": "1.0.0-rc3",
```

my webpack config
```
var webpack = require('webpack');
var path = require('path');

var ExtractTextPlugin = require("extract-text-webpack-plugin");

var PORT = process.env.PORT || 8888;
var HOSTNAME = process.env.HOSTNAME || "localhost";
var APP_PATH = path.resolve(__dirname, 'src');
var ENTRY_PATH = path.resolve(__dirname, 'src', 'client', 'index.js');
var NODE_MODULES_PATH = path.resolve(__dirname, 'node_modules');
var BUILD_PATH = path.resolve(__dirname, 'public', 'scripts');

var sassLoaders = [
  "css-loader",
  "autoprefixer-loader?browsers=last 2 version",
  "sass-loader?sourceMap&outputStyle=expanded&" +
  "includePaths[]=" +
  encodeURIComponent(path.resolve(__dirname, "./node_modules/")) + "&" +
  "includePaths[]=" +
  encodeURIComponent(path.resolve(__dirname, "./src/"))
];

module.exports = {
  name: 'client',
  context: __dirname,
  devtool: 'inline-source-map',
  target: 'web',
  debug: true,
  cache: true,

  entry: [
    "webpack-dev-server/client?http://" + HOSTNAME + ":" + PORT,
    'webpack/hot/only-dev-server',
    ENTRY_PATH
  ],
  output: {
    filename: 'bundle.js',
    path: BUILD_PATH,
    publicPath: "/scripts/"
  },

  module: {
    preLoaders: [
      {
        test: /\.(js|jsx)$/,
        loaders: ['eslint-loader'],
        include: APP_PATH,
        exclude: [NODE_MODULES_PATH]
      }
    ],
    loaders: [
      {
        test: /(\.jsx|\.js)$/,
        loaders: ['react-hot', 'babel-loader?stage=0'],
        exclude: [NODE_MODULES_PATH]
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract("style-loader", sassLoaders.join("!")),
      },
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      },
      {
        test: /\.(png|jpg)$/,
        loader: "url-loader?limit=8192"
      },
      {
        test: /\.woff$|\.ttf$/,
        loader: 'file-loader?limit=100000'
      }
    ]
  },

  plugins: [
    new webpack.DefinePlugin({
      __DEV__: JSON.stringify(JSON.parse(process.env.BUILD_DEV || 'true')),
      __PRERELEASE__: JSON.stringify(JSON.parse(process.env.BUILD_PRERELEASE || 'false')),
      __CLIENT__: true,
      __SERVER__: false
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new ExtractTextPlugin('main.css', {
      allChunks: true
    })
  ],

  resolve: {
    modulesDirectories: ["src", "node_modules", "modules"],
    alias: {},
    root: [
      path.resolve(__dirname, 'node_modules'),
      path.resolve(__dirname, 'src', 'modules'),
      path.resolve(__dirname, 'src')
    ],
    extensions: ['', '.js', '.jsx', '.scss']
  },

  eslint: {
    configFile: '.eslintrc'
  },

  devServer: {
    contentBase: "./public",
    hot: true,
    inline: true,
    lazy: false,
    quiet: false,
    noInfo: false,
    headers: {"Access-Control-Allow-Origin": "*"},
    stats: {colors: true},
    host: HOSTNAME,
    historyApiFallback: true,
    port: PORT
  }
};
```

Let me know if it works for you or you get some better setup.
cheers

**Comment by mingfang** [comment]
+1 to get grommet working with React 0.14 and Webpack

**Comment by AngusMackHPE** [comment]
@primozs thanks for your detailed reply and sorry it has taken a while to get back. I got this working relatively easily in the end. I used the react-rocket-boilerplate project as a base and was able to use grommet as a lib for my project.

Had to keep react dependency at ^0.13.0 which is a bit of a pain as would like to move to 14 for some other dependent libs but all in all good so far.

**Comment by thiagoc7** [comment]
@alansouzati thanks for this amazing library!
I git it a try using gaearon's [boilerplate](https://github.com/gaearon/react-transform-boilerplate), react 0.14, and it is working just fine, no issues at all.
[here](https://github.com/thiagoc7/react-grommet-todo) the repo I created, it's the official todo using webpack and alt.

Thanks!

**Comment by Spy-Seth** [comment]
@alansouzati I've converted my project to browserify that I know better, I will give another try on it in the next week.

**Comment by alansouzati** [comment]
cool stuff @thiagoc7! It is interesting that you also add `alt` containers with store on that example. Good job!

**Comment by alansouzati** [comment]
@Spy-Seth looking forward to hearing more about integration with Browserify! ;)

**Comment by linde12** [comment]
Any news about this? I wish to use grommet as a library so i can use all the components in my projects with browserify and babel.

Right now i do something like:

```
import App from 'gormmet/components/App';
import Header from 'gormmet/components/Header';
```

What i would expect is:
`import {App, Header} from 'grommet';`

I also don't get the css included by doing this(obviously).

Maybe the grommet components could be a separate repo which grommet depends on? I'm not sure what's best but i'd really like to use Grommet's awesome components! :)

**Comment by primozs** [comment]
@linde12 
Hi, maybe this helps?
https://github.com/primozs/react-hello/tree/step4-grommet

**Comment by alansouzati** [comment]
Hi @linde12 both

```
import App from 'grommet/components/App';
import Header from 'grommet/components/Header';
```

and 

```
import {App, Header} from 'grommet';
```

should be supported.

Our recommended approach is to use like this `import Header from 'grommet/components/Header';` so you save size in your final bundle. Regardless if you are using Browserify or Webpack, if you do: `import {App, Header} from 'grommet';` you load the entire grommet library and then filter it down to App and Header.

I would say this issue is fixed, we have full support for Grommet as a library a long a time ago.

What sort of issues are you facing? Would you mind sharing that with us?

**Comment by linde12** [comment]
@alansouzati 
@primozs 

Thanks for the quick replies. I tried using the ES6 `import {A, B} from 'C'` in my app but didn't manage to get it working. I will try tomorrow again and get back at you if i still encounter the problems. Most likely it's bad usage on my part.

@primozs 
Is it okay to clone your lib and use it as a base? It's pretty much exactly what i want. Redux, Grommet, React, ES6... Then i'll just have to add Traverson for HATEOAS! :+1:

**Comment by primozs** [comment]
@linde12 sure you can use it however you want. Cheers

**Comment by Spy-Seth** [comment]
@alansouzati Sorry to not answer you sooner. My project that start using grommet was canceled. I'm still fan of this lib, I will give it another try when I can.

**Comment by linde12** [comment]
@alansouzati 

Ah, today i tried again and the `import {App, Header} from 'grommet';` still doesn't work but it seems it's due to another error i get when importing some other components that uses icons:
`
Cannot resolve 'file' or 'directory' ./icons/base/Up in /path/to/project/node_modules/grommet/components @ ./~/grommet/components/Article.js 47:10-36`

Before i ran browserify and thought that might be the problem(because of the grommet-icon-loader npm module for webpack) but even using @primozs webpack-config i still get this error. I also went to the [grommet-icon-loader rep](https://github.com/grommet/grommet-icon-loader) and added the loader specified there to the webpack-config without any luck.

I wish i could run it with browserify, but if that's not possible then it'd be cool if i could get it running with webpack.

Do you have any clues to what the problem might be?

**Comment by primozs** [comment]
@linde12 To se see how to import something I am often using:
http://www.grommet.io/docs/develop
http://www.grommet.io/docs/develop/icon
http://www.grommet.io/docs/develop/app
https://github.com/grommet/grommet-docs (source of the previous link, very useful)

for app and icon it should be imported like this:
```
import App from 'grommet/components/App';
or
var Action = require('grommet/components/icons/base/Action');
import Action from 'grommet/components/icons/base/Action';
```

**Comment by linde12** [comment]
@primozs Ah, yes, sorry for not being clear. I'm trying to use the `Article` component which, in it's turn, seems to be importing `./icons/base/Up` but doesn't manage to import it properly.

It's basically what we've got over at [http://www.grommet.io/docs/develop/sidebar](the docs for Sidebar)

So when i do `import Article from 'grommet/components/Article';` i get the error mentioned in the previous comment.

**Comment by alansouzati** [comment]
I see, i'm not that much familiar with Browserify. I guess it is failing to recognize `./`. I'm not sure if this is a webpack-specific approach to refer to local folders. Are you guys familiar with Browserify? Do you think this could present issues?

You don't need a special loader for `./icons/base/Up`, you can see it [here](https://github.com/grommet/grommet/blob/stable/components/icons/base/Up.js), it is just regular compiled babel source.

I know in webpack I have to configure my known extensions, is there something similar to Browserify? You can see all our import commands do not provide extensions.

**Comment by linde12** [comment]
@alansouzati Ah i see, then it should be no problem at all... Hmm! Regarding browserify it should work right off the bat then. I also tried with webpack but i get the same error. I will give a detailed error message once i'm home in a few minutes!

Thanks for all the help so far!

**Comment by linde12** [comment]
[Here is a picture](http://i.imgur.com/SHEQ9QI.png) where you can see some of the code(basically just the `import` that is interesting) and the error message i receive afterwards.

**Comment by alansouzati** [comment]
Really weird,
 
   Can you verify this file is actually present?

`/home/linde/go/src/ioboxrevel/public/node_modules/grommet/components/icons/base/Up.js`

If it is there, I'm afraid that could be some configuration issue with Browserify. 

I will try soon to get grommet working with Browserify, but I'm not sure how soon. :smile:

**Comment by zalmoxisus** [comment]
I confirm the same error with Webpack. The file really doesn't exist. It should be `/icons/Up.js`.

Can send a PR to fix it, if you don't mind.

**Comment by linde12** [comment]
@alansouzati I'm afraid it's as @zalmoxisus suggests! `stat /home/linde/go/src/ioboxrevel/public/node_modules/grommet/components/icons/base/Up.js` gave me a `No such file or directory` error!

However it exists at icons/Up.js

**Comment by alansouzati** [comment]
Cool glad we are getting down to the issue.

It is really weird to be missing. I remember we had this issue in the past, can you confirm your Node and NPM versions? Also can you confirm the Grommet version you are trying to install?

The one at `icons/Up` is deprecated and we will be removing it in the next version.

If you look here: https://github.com/grommet/grommet/blob/stable/components/icons/base/Up.js

The icon does exist. :cry:

**Comment by linde12** [comment]
@alansouzati Yeah, getting there! :)

I'm using node v5.6.0, npm 3.6.0.

I installed grommet from npm via `npm install --save grommet` and `./node_modules/grommet/bin/grommet.js --version` yields 0.5.4

**Comment by alansouzati** [comment]
https://github.com/grommet/grommet/issues/292

**Comment by alansouzati** [comment]
https://github.com/npm/npm/issues/11135

**Comment by linde12** [comment]
Ah, i see! Weird! Is there anything i can do manually to retrieve the icons?

**Comment by alansouzati** [comment]
Let me investigate it further, I will release 0.5.5 to fix that, even if it means I will have do to it manually :smile:

**Comment by linde12** [comment]
Oh! Hope it's not too much trouble, heh!

**Comment by alansouzati** [comment]
I've release 0.5.5 with NPM can you give it a try again ?

**Comment by linde12** [comment]
On it..!

**Comment by linde12** [comment]
Wohoo! Now everything works! :) Both `import * as Grommet from 'grommet';`(even though i won't be using it) and the `Article` import doesn't yield errors! Works fine with Browserify.

Success, hehe!

**Comment by alansouzati** [comment]
Cool! I'm going to close the issue (for now) ahahha

**Comment by zalmoxisus** [comment]
@alansouzati, thanks for fixing the problem with icons! Could you also push the changes corresponding to the version tag? I don't see [these changes](https://github.com/grommet/grommet/commit/48dafc14c165ead3c9cbde14d9731ff3e19999a4) in `grommet@0.5.5`, though it correspond to `v0.5.5` tag.

So, I get the following behaviour:
<img width="494" alt="screen shot 2016-03-24 at 1 03 11 pm" src="https://cloud.githubusercontent.com/assets/7957859/14015381/14851566-f1c1-11e5-9b92-84048d722932.png">

According to the demo, the buttons should have the same height regardless of having an icon inside or not.

**Comment by RyanCCollins** [comment]
Hi folks, just as a follow up is there a recommended way to load the grommet styles into a project?  I am using ES6 default imports, but the styling is not coming with it.  I really love your project and plan to use it on my next big work gig.  Thanks so much!

**Comment by alansouzati** [comment]
You need a scss-loader. ES6 only will not bring styles. Are you using webpack?

**Comment by CoveTechnologyAus** [comment]
I have the same problem, I am using scss-loader like the below in webpack but the styles are not being recognized. If I directly import grommet.min.css into index.html it works ok.

{
        test: /\.scss$/,
        loader: 'style!css!sass?outputStyle=expanded&' +
          'includePaths[]=' +
          (encodeURIComponent(path.resolve('./node_modules')))
      },

**Comment by RyanCCollins** [comment]
Hi! Thanks for getting in touch with me! I sure am using Webpack along with an scss loader, but I'll have to get back to you when I'm at the computer regarding the configuration and the error I'm seeing.  I was able to get the styles up and running with just the compiled CSS, so that should work temporarily. Thanks again!

**Comment by Eliraz-TTK** [comment]
how do you install grommet as a webpack library? I dont get it.

**Comment by alansouzati** [comment]
Let me work on creating a standalone sample project that you guys can refer to.

I will also create a wiki page describing what you need to do in order to get grommet styles running.

**Comment by RyanCCollins** [comment]
Hi @alansouzati!  That's spectacular! I think that would serve the open source community well. We want to integrate grommet into a component library we are using for a distributed open source team and your contributions will go a long way towards that effort. I really appreciate it!

**Comment by alansouzati** [comment]
Cool great to hear that. Which open source team is it? Would love to learn more about it :)

**Comment by alansouzati** [comment]
grommet-standalone has been created and it should be available for reference on how to use grommet with webpack

https://github.com/grommet/grommet-standalone

**Comment by RyanCCollins** [comment]
Thanks so much @alansouzati. That's super helpful!  What a great project this is! 

As far as the open source, I'm part of two open source conmunities. One is an organization called HackSmiths and the other is for alumni of Udacity, an online MOOC, which gives our graduates an opportunity to work on a collaborative project.

Thanks again, I'm a big admirer and am so happy to have found a react based UX framework!

**Comment by olifante** [comment]
Grommet looks really great. Do you guys know how to make it work as a UI library together with [next.js](https://github.com/zeit/next.js)? It makes it even easier to get started with universal React apps than creat-react-app. It's pretty simple to use Rebass or MuiCSS with next.js, but I'm not sure how well Grommet would play with next.js.

**Comment by tracybarmore** [comment]
Hi @olifante. Would you mind posting this question in either Grommet's #general Slack channel or opening up a new issue? I caught this question on the off-chance of looking through closed issues, so it would have normally gone unnoticed. Thanks!

**Comment by olifante** [comment]
@tracybarmore thanks for the tip, I posted the question on Slack.

**Comment by david-cahill** [comment]
@olifante any update on using grommet with next.js? I'm having issues using grommet components as they don't seem to be ssr compatible
