### ISSUE TITLE
v2 TextInput - suggestions not updated from componentWillReceiveProps

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2039]
TextInput only resets the suggestions in onInput
Use case when using `<TextInput />` for searching remote API data is to launch a new query from the onInput and when a new set of suggestions is retrieved to update the suggestions props. 
Please check in componentWillReceiveProps to call the resetSuggestions function.

Use case: https://github.com/atanasster/crypto-grommet/blob/master/components/entities/SearchEntity.js

**Comment by karatechops** [comment]
Just a note here - v2 has a peer dependency of 16.3, we should be debugging this with `getDerivedStateFromProps` instead of the cwrp lifecycle method.

**Comment by ericsoderberghp** [comment]
I just tested this by responding to changing the suggestions in reaction to onChange but doing it via a timer, to simulate the server interaction. When the suggestions property was updated, the suggestions shown reflected that without any user interaction needed. So, I believe this has been fixed.

**Comment by atanasster** [comment]
Still not fixed. just tested again. you can test with a rest api being called in response to TextInput onChange={this.onSearch}. I have several use cases in my repos and still need to use my cloned version of TextInput

**Comment by alansouzati** [comment]
Closing this, let's track here https://github.com/grommet/grommet/issues/2247.

Feel free to reopen if you think it is a different bug
