### ISSUE TITLE
drop down Menu auto dropAlign according to screen position

### ISSUE THREAD

**Issue by 2manoj1** [grommet/grommet#3008]
In Menu default list come at bottom position if scroll-able screen is reached to window screen then automatically list should display at top.
Also change automatically when the user scrolls or resizes window.

Currently we have dropAlign props to set the position of Menu but how I decide to set drop Align when Menu in scrollable list and scrollable list dynamic nature.

### Expected Behavior

- If no space below we should auto adjust Menu and open in top.
- Or provide onOpen callback function where we decide dropAlign position and set again, re-render Menu
### Actual Behavior

- Menu not properly visible when Menu Height more and open near to window screen.
### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/llq6x53x99

### Your Environment

- Grommet version: 2.4.0
- Browser Name and version: Google Chrome 73.0.3683.103 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by oorestisime** [comment]
Onopen callback seems to be a nice addition for menu

**Comment by ShimiSun** [comment]
Since Menu uses DropButton, and I think you already filed a similar issue of Select #2994 that is also using DropButton and was fixed on [PR](https://github.com/grommet/grommet/pull/3028). I suspect we can close this issue, would you like to verify? @mrebb I think you can also contribute to the conversation :)

**Comment by 2manoj1** [comment]
@ShimiSun After Next release I will test and update the ticket otherwise provide the environment where will test  below codesandbox. https://codesandbox.io/s/llq6x53x99

**Comment by mrebb** [comment]
@2manoj1,  as @ShimiSun mentioned this should be automatically resolved as part of [PR](https://github.com/grommet/grommet/pull/3028) since both Select and Menu use DropButton. You can pull `master` branch and test locally if you plan to test before next release.

**Comment by 2manoj1** [comment]
@mrebb @ShimiSun Tested this in locally with latest master branch and update the storybook with my example, I got below result
![image](https://user-images.githubusercontent.com/15128569/56557728-d6496480-65b9-11e9-8f80-b081fef15704.png)

Look like this issue not fixed.

- Below file contains example of list with Menu
[menu.stories.js.zip](https://github.com/grommet/grommet/files/3106015/menu.stories.js.zip)

**Comment by mrebb** [comment]
@2manoj1 Here is the [video](http://recordit.co/5mhwlbyd8p) and I don't see the issue with same example. Do you see the below code as part of DropContainer.js?

**Comment by 2manoj1** [comment]
@mrebb this is correct, this issue was different. see at end of scroll or check the last list item, open the menu its not auto adjusted, no space in below so I want auto flip the menu to top.

I take latest master branch code and run storybook with my example.
