### ISSUE TITLE
Stack anchor is offset

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#4372]
### Expected Behavior

When setting the `anchor="top-right"`, the expectation is that the stacked element will sit in the top-right position.

### Actual Behavior

When setting the `anchor="top-right"`, the stacked element is offset from the top-right position.  The workaround is to wrap the stacked element with a `Box`.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/stack-anchor-needs-a-box-orfyy

![image](https://user-images.githubusercontent.com/8231064/89230293-5c11e780-d626-11ea-83e3-f6d10dbffb15.png)

Here is the snippet:

```
      <Heading level="2">Top-Right: Not working</Heading>
      <Button>
        <Stack anchor="top-right">
          <Notification />
          <StatusGoodSmall color="red" size="small" />
        </Stack>
      </Button>
      <Heading level="2">Top-Right: Works when wrapped</Heading>
      <Button>
        <Stack anchor="top-right">
          <Notification />
          <Box>
            <StatusGoodSmall color="red" size="small" />
          </Box>
        </Stack>
      </Button>
```

### Steps to Reproduce

See codesandbox.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome and Firefox
- Operating System and version (desktop or mobile): Windows 10

**Comment by LiveFreeAndRoam** [comment]
Some more data points after a chat with Shimi...

> One thought regarding this issue is that the default props of icon may cause it. If you'll replace the usage of SmallStatusIcon with simply a <Box pad='xsmall' round='full' background='green' /> that should work without the wrapper, can you give it a try?

I tested it and here are my findings...

1. The stacked element is a `Box`, so it seems to be the same solution as wrapping the stacked icon in a `Box`.  Perhaps this should be a mandatory requirement to wrap stacked elements in `Box`?

2. When using a `Box` without any children, you need `pad='xsmall'` , to give the box a dimension that can be filled.  This is not immediately intuitive.

3. The dimension of `<Box pad="small">` is larger than the dimension of `<Icon size="small">`.  While that is not a big deal here, it may be a factor in stacks that need more precise positioning.

![image](https://user-images.githubusercontent.com/8231064/89239338-3a235f80-d63c-11ea-8cd4-0a64d0b59805.png)

**Comment by ShimiSun** [comment]
@britt6612, can you confirm this issue is solved with your recent PR as well?

**Comment by britt6612** [comment]
<img width="678" alt="Screen Shot 2020-08-06 at 1 55 53 PM" src="https://user-images.githubusercontent.com/42451602/89576459-8c0ae780-d7ec-11ea-8908-b1a58a7c1748.png">

Unfortunately no I believe its some thing similar when wrapped in a button but since this is using stack.
The other example was using button 
```

        <Button
          icon={
            <Stack anchor="top-right">
              <Notification />
              <Box>
                <StatusGoodSmall color="red" size="small" />
              </Box>
            </Stack>
          }
        />

```

I can look more into this though!

**Comment by narayand16** [comment]
Is this bug still alive ? If yes, I can dig into it. While going through the conversation above, I see that stacked element can be placed in a box or box element can be used directly without any wrapper while using some other props(pad etc).

@ShimiSun, @ericsoderberghp What are we planning to use then ?

**Comment by LiveFreeAndRoam** [comment]
Yes, it's still a problem.  Here is a codesandbox where the Box wrapper was needed.

https://codesandbox.io/s/7e650l

**Comment by LiveFreeAndRoam** [comment]
Another example where Stack is not working consistently between the Button and Menu components:

[Badge with Button vs Menu](https://v2.grommet.io/menu?c=DwIQ9gHgBAJglgJwKYGMAucwDsC8AiBMAdzwD4AoKKUSKAIzARiQQqqtAFc01tL2qcFNhwBvYAElhWAM4A6AArEWUAPSkAvvwF0AhjADmSMaL0oA1gcKcsMAFxQA5DLS60nGQFow5xwBooADddABtOJAc0BHCNLQF1fmBVcAg2ahT6RmZWbWoAWSQsTlzBaTFJaXklIhV1OIF6fSMTM0trWwdnV3cvIl0ELDgsA38g0PDI6KRYkqg4NCQAWxkxAG1ZqlEoEN06JBDOgDFEFygAQXRMLFHsAGEQoXMHAAokAEooHFIoUUqwEKQchCYAMz0c4DAo0BrgQRjQciGWBYAAkACp5AAybw0UA0fg2P22u32nQAyqhsDBzpdsDcsPdHi8Pl8fji8bMALr1KgJDjJSAUJIpUhAA)

![image](https://user-images.githubusercontent.com/8231064/200717669-d9e91c16-97d8-4217-b0c8-e9ecba0693d5.png)
