### ISSUE TITLE
getting start docs terminate in somewhat of dead end.

### ISSUE THREAD

**Issue by cdaringe** [grommet/grommet#963]
### Expected Behavior

i expected to see a workflow of how and why grommet would be a good solution for me.

### Actual Behavior

- i read getting started (the install docs, bower or npm)
- i visited & read the architecture page

i then didn't know what to do next.  i am wondering what exactly the outputs of using grommet are, and how they can help me and my team.

**Comment by alansouzati** [comment]
Thanks for raising this topic. Just to be clear, the "how" aspect of things you were able to complete correct? Meaning you are able to install grommet, but you would like to understand why you have to use it?

I think we are doing a good job in terms of "how", but you are not the first want that is complaining about the "why". We will work on adding it to our site as soon as possible.

If you think the "how" is not clear, I kindly request feedback on what you would do to enhance our get started page.

**Comment by cdaringe** [comment]
hey @alansouzati, thanks for writing back.  indeed, you are correct.  the "how" to install and run was clear.  the "why" i should use it was is not clear.  the homepage doesn't tell me what it is, nor do i think the "build something now" was indicative of the value i get from the tool.

i'm guessing (hoping?) this is some sort of pattern-lib + component-api tooling that can be used for FE development between UX & engineering teams?

anyway, hope i didn't come off rude, just sharing my experience

**Comment by alansouzati** [comment]
You did not come off rude at all, this kind of feedback is extremely useful.

While we don't have it on the site, this is what I believe is the "why you should care about Grommet":

1) **Unified**: we are more than just a UI widget library for React. We are a User Experience framework that aims to bridge the gap between design and development. We offer patterns like: Navigation and Login. We also offer templates and sample apps for higher order component interaction.
2) **Modular**: we run on top of Node and we provide all the components independently, which means that you only pay for what you use.
3) **Accessible**: We take accessibility as a core functionality and if you use Grommet you are in a good path to meet the WCAG standards. Check out this video we published recently: https://vimeo.com/187068246.
4) **Community-Driven**: We provide trainings and support to the community even if it is not directly related to Grommet. For example, we constantly find ourselves on slack helping folks get a better understanding of good UX practices. Checkout all our videos at: https://vimeo.com/187068246. Also, join our slack community: http://slackin.grommet.io.

**Comment by bryanjacquot** [comment]
Also think about including:
.  Responsive design without the complexity of managing breakpoints and grids.
 . Themes allow you to stay true to your design esthetic and brand
 . Curated design and development platform with attention to details in typography, color, spacing, and interaction.
 .  Engaged community ready to assist designers and developers onboard along with sticker sheets, command line tools, and ready-to-run developer toolbox.

**Comment by alansouzati** [comment]
PR pending https://github.com/grommet/grommet-docs/pull/173

**Comment by alansouzati** [comment]
Thanks for the feedback you all. we've merged the pull request.

**Comment by cdaringe** [comment]
hey @alansouzati, thanks for beefing up the page with some info!  i waltzed through the changes and looked at the vimeo channel, but still, I was not clear how to achieve that which I came for originally.

> We are a User Experience framework that aims to bridge the gap between design and development

This is the key claim that interests me.  Component lib + ux playground.  The docs still do not direct me to instructions on how to achieve/explore this.  Of course I don't expect the docs to completely hold my hand, but some direction would be appreciated!
