### ISSUE TITLE
Sidebar component color contrast detection incorrect/inconsistent

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet#989]
### Expected Behavior

Contrast between link color and sidebar background should be calculated correctly
### Actual Behavior

Consistently in Firefox, a sidebar with a dark background will also have dark text.
In chrome, on initial component mount, a sidebar with a light background will have light text. Once a rerender is triggered for the sidebar in Chrome, the color contrast corrects itself.
### URL, screen shot, or Codepen exhibiting the issue

I was unable to create a Codepen to illustrate the issue
![hellfire - firefox - oct 18 2016 1 16 02 pm](https://cloud.githubusercontent.com/assets/4998403/19492832/9661e524-9535-11e6-9fdb-470f91a0034c.png)
![hellfire - firefox - oct 18 2016 1 16 01 pm](https://cloud.githubusercontent.com/assets/4998403/19492833/9661fe06-9535-11e6-8827-b89d6aeb72b3.png)
### Your Environment

- Grommet version: 1.0.0
- Browser Name and version: Chrome and Firefox 
- Operating System and version (desktop or mobile): OSX

**Comment by davidcalhoun** [comment]
Could you double check to make sure that the CSS isn't being loaded after the JS?  The CSS should be in the document `<head>` before any JS.

I was able to reproduce the issue in this Codepen by dynamically adding the CSS stylesheet after the React code: http://codepen.io/franksvalli/pen/VKqEzX

Codepen in Chrome:
<img width="528" alt="screen shot 2016-10-21 at 5 56 56 pm" src="https://cloud.githubusercontent.com/assets/120596/19615714/661f9ae8-97b8-11e6-8a77-07a1d4310efb.png">

Codepen in Firefox:
<img width="349" alt="screen shot 2016-10-21 at 5 57 45 pm" src="https://cloud.githubusercontent.com/assets/120596/19615715/6b14f692-97b8-11e6-9d55-8a4116884240.png">

**Comment by ericsoderberghp** [comment]
I thought we fixed this by hinting at the color context initially before detecting it later. We should investigate.

**Comment by tracybarmore** [comment]
We believe this issue has been fixed. @nickjvm can you verify with grommet stable?

**Comment by nickjvm** [comment]
@tracybarmore it looks like the contrast detection for light sidebars is fixed with grommet stable, but still seeing the same issue with dark colored backgrounds.

![screen shot 2016-11-30 at 9 34 24 am](https://cloud.githubusercontent.com/assets/4998403/20761449/41ca09fc-b6e0-11e6-8bb2-a2534b8a43af.png)

**Comment by ericsoderberghp** [comment]
@nickjvm Can you check this again? We made some more changes and can't reproduce the issue.

**Comment by nickjvm** [comment]
@ericsoderberghp I appreciate your attention on this. Unfortunately I'm still seeing the same issue in Firefox. Can you think of anything I can provide or try out on my end that would help you to replicate the issue?

**Comment by ericsoderberghp** [comment]
Ideally, a CodePen. Otherwise, how about a static file I can run locally?

**Comment by nickjvm** [comment]
I'll see if I can get something together to replicate the issue.

**Comment by tracybarmore** [comment]
Hey @nickjvm, thanks for all your collaboration with us. We will be cleaning up our backlog first week of February 2017 by closing unresponsive issues that haven't been active for at least 30 days.

If you would like this issue to remain open in our backlog, please comment to let us know. Thanks!

**Comment by nickjvm** [comment]
@tracybarmore Thanks for following up on this! It's definitely still an issue for us, so I'd like to keep it open. 

I was able to create a very simplified version of our environment to replicate the issue. Please check out the repo here: https://github.com/nickjvm/grommet-color-contrast. As you can see, with the latest version of Grommet, Firefox is still giving us an issue in both Windows and OS X:

![](http://i.imgur.com/KVbyeOU.png)
![](https://camo.githubusercontent.com/0f619567c3ce3c763e911e9146a775c6d6532f21/687474703a2f2f692e696d6775722e636f6d2f657158507370752e706e67)

**Comment by tracybarmore** [comment]
@nickjvm, great. I'll keep it in our backlog and get one of the guys to address it during our backlog grooming session. Thanks!

**Comment by ericsoderberghp** [comment]
@nickjvm I was able to reproduce it with the repository you sent, thanks. However, I was unable to link that repository to my local grommet to dig into it. So, I created a new repository using `grommet new` and then copied over the relevant components from yours. But, I can no longer reproduce the problem. It appears there's something different in your environment than mine. I'm still digging into it more. You can see the one I built here:

https://github.com/ericsoderberghp/grommet-backgrounder.git

Also, I noticed that you had multiple grommet App components in yours. There should only be exactly one.

**Comment by nickjvm** [comment]
@ericsoderberghp Thanks for digging into it.

I ran your repo and was also not able to replicate. I'll compare webpack configs and see if there's something that sticks out that is different. The setup we're using came from `grommet-toolbox`.

Thanks for pointing out the extra `<App />`. I think that was just a bad copy/paste when I was trying to shrink the code for demo purposes. Our real app only has one 😄

**Comment by tracybarmore** [comment]
Hey @nickjvm, sorry to be 'that guy', but we will be cleaning up our backlog next week by closing unresponsive issues that haven't been active for at least 30 days. If you would like this issue to remain open in our backlog, please comment to let us know. Thanks!

**Comment by nickjvm** [comment]
@ericsoderberghp @tracybarmore We upgraded to 1.3.1 today, and after some brief testing, it appears to be resolved. If it continues to be an issue, I will reopen the issue.
